import assert from 'node:assert/strict';
import core from './dist/membership-core.js';
const good={real_name:'홍교사',institution:'생물고등학교',phone:'010-1234-5678',interest:'생물 수업 활용',introduction:'탐구 수업',consent:true};
assert.equal(core.validateApplication(good).phone,'01012345678');
for(const phone of ['', 'abc01012345678', '010123', '<script>', '9'.repeat(30)])assert.throws(()=>core.validateApplication({...good,phone}));
assert.equal(core.validateApplication({...good,phone:'02-123-4567'}).phone,'021234567');
const clean=core.validateApplication({...good,user_id:'someone-else',status:'approved',is_admin:true});
assert.equal(clean.status,undefined);assert.equal(clean.user_id,undefined);assert.equal(clean.is_admin,undefined);
assert.equal(clean.consent_version,'2026-10-06');
assert.throws(()=>core.validateApplication({...good,real_name:'  '}));
assert.throws(()=>core.validateApplication({...good,consent:false}));
assert.throws(()=>core.validateApplication({...good,introduction:'가'.repeat(501)}));
assert.equal(core.escape('<img src=x onerror="alert(1)">'),'&lt;img src=x onerror=&quot;alert(1)&quot;&gt;');
assert.equal(core.canParticipate({user:{id:'one'},membership:{status:'pending'}}),false);
assert.equal(core.canParticipate({user:{id:'one'},membership:{status:'suspended'}}),false);
assert.equal(core.canParticipate({user:null,membership:{status:'approved'}}),false);
assert.equal(core.canParticipate({user:{id:'one'},membership:{status:'approved'},error:'Failed verification'}),false);
assert.equal(core.canParticipate({user:{id:'one'},membership:{status:'approved'}}),true);
assert.equal(core.configured({supabaseUrl:'https://project.supabase.co',supabasePublishableKey:'sb_secret_example'}),false);
assert.equal(core.configured({supabaseUrl:'https://project.supabase.co.evil.example',supabasePublishableKey:'sb_publishable_example'}),false);
assert.equal(core.configured({supabaseUrl:'https://project.supabase.co',supabasePublishableKey:'sb_publishable_example'}),true);
const gate=core.createRequestGate();
const first=gate.capture('community'),second=gate.capture('community');
assert.equal(first(),false);assert.equal(second(),true);
gate.invalidate('community');assert.equal(second(),false);
const privatePost=gate.capture('private-post');gate.invalidateAll();assert.equal(privatePost(),false);
assert.equal(gate.capture('private-post')(),true);
console.log('PASS membership input, HTML escaping, fail-closed UI states, and public configuration validation.');
